Luis
robscafe433/react-e-store pull request #16
Opened 2022-01-18 06:33 UTC by VelazquezLuis

Categories and Category file, updated. they now fetch the info from the server.

Added Function to Title case each category.

Moved Footer to be the last child div in home.

2022-01-19 08:12 UTC, robscafe433 reviewed
Reviewed code,  noticed you are now passing info from props.

2022-01-20 16:45 UTC, HeyItsFelipe requested changes

2022-01-20 16:45 UTC, HeyItsFelipe commented on src/components/Categories/categories.js
> +            return <Category index={index} item={item}/>;
Change index={index} to key={index}.  It will fix an error.  https://reactjs.org/docs/lists-and-keys.html

2022-01-22 07:47 UTC, VelazquezLuis commented on src/components/Categories/categories.js
> +            return <Category index={index} item={item}/>;
Hi Felipe, updated code please review.

2022-01-22 18:19 UTC, HeyItsFelipe approved these changes

2022-01-22 18:23 UTC, merged